dist: trusty
language: rust
rust:
  - 1.16.0
  - 1.17.0
  - 1.18.0
  - 1.19.0
  - 1.20.0
  - 1.24.0
  - stable
  - beta
  - nightly
cache: cargo
script:
  - cargo test --verbose
  - cargo test --verbose --features allocator_api
  - cargo test --verbose --features allocator_api,fallible --no-default-features
  - if [ $TRAVIS_RUST_VERSION = "nightly" ]; then cargo test --verbose --features unstable-rust; fi
  - if [ $TRAVIS_RUST_VERSION = "nightly" ]; then cargo test --verbose --features unstable-rust,fallible; fi
