dist: trusty
language: rust
rust:
  - 1.10.0
  - 1.15.0
  - 1.20.0
  - 1.25.0
  - beta
  - nightly
cache: cargo
script:
  - cargo test --verbose
  - cargo test --verbose --features unstable-rust
  - cargo test --verbose --features allocator-api
  - cargo test --verbose --features allocator-api,fallible --no-default-features
  - if [ $TRAVIS_RUST_VERSION = "nightly" ]; then cargo test --verbose --features unstable-rust; fi
  - if [ $TRAVIS_RUST_VERSION = "nightly" ]; then cargo test --verbose --features unstable-rust,fallible; fi
