dist: trusty
language: rust
matrix:
  include:
  - rust: 1.20.0
  - rust: 1.21.0
  - rust: 1.22.0
  - rust: 1.23.0
  - rust: 1.24.0
  - rust: 1.25.0
  - rust: 1.26.0
    env: ALLOCATOR_API=1
  - rust: stable
    env: ALLOCATOR_API=1
  - rust: beta
    env: ALLOCATOR_API=1
  - rust: nightly
    env: ALLOCATOR_API=1
cache: cargo
script:
  - cargo test --verbose
  - if [ "$ALLOCATOR_API" ]; then cargo test --verbose --features allocator_api; fi
  - if [ "$ALLOCATOR_API" ]; then cargo test --verbose --features allocator_api --no-default-features; fi
