dist: trusty
language: rust
rust:
  - 1.21.0
  - 1.22.0
  - 1.23.0
  - 1.24.0
  - 1.25.0
  - beta
  - nightly
cache: cargo
script:
  - cargo test --verbose
  - cargo test --verbose --features allocator_api
  - cargo test --verbose --features allocator_api,fallible --no-default-features
  - if [ $TRAVIS_RUST_VERSION = "nightly" ]; then cargo test --verbose --features unstable-rust; fi
  - if [ $TRAVIS_RUST_VERSION = "nightly" ]; then cargo test --verbose --features unstable-rust,fallible; fi
